anime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('choose_anime.urls'))
]

choose_anime/urls.py
from django.urls import path

from . import views

app_name = 'choose_anime'

urlpatterns = [
    path('', views.home, name='home'),
    path('cadastrar-anime/', views.cadastrar_anime, name='cadastrar-anime'),
    path('assistir-aleatorio/', views.random_template, name='random-anime'),
]

choose_anime/models.py
from django import forms
from django.db import models

# Create your models here.


class Category(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)


class Animes (models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=255)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, default=None)


class AnimeForm(forms.ModelForm):
    class Meta:
        model = Animes
        fields = "__all__"

choose_anime/views.py

from django.shortcuts import render

from .models import AnimeForm, Animes
from .utils.animes.functions import randomize


def home(request):
    animes = Animes.objects.all()
    return render(request, 'animes/home.html', context={
        'anime': animes
    })


def random_template(request):
    lista = Animes.objects.all()
    context = {
        'item': randomize(lista),
    }
    return render(request, 'animes/random.html', context=context)


def cadastrar_anime(request):
    if request.method == "GET":
        form = AnimeForm()
        context = {
            'form': form
        }
        return render(request, 'animes/form.html', context=context)
    else:
        form = AnimeForm(request.POST)
        if form.is_valid():
            form.save()

        context = {
            'form': form
        }
        return render(request, 'animes/form.html', context=context)

choose_anime/templates/animes/footer.html
<footer class="footer-container">
    <h2><a href="{% url 'choose_anime:home' %}">Voltar</a></h2>
    <h2><a href="{% url 'choose_anime:cadastrar-anime' %}">Cadastrar novo anime</a></h2>
    <h2><a href="{% url 'choose_anime:random-anime' %}">Qual anime assistir?</a></h2>
</footer>

choose_anime/templates/animes/form.html

{% include 'animes/head.html' %}
<div class="container">
    <form class="form-container container"action="." method="post">
        <h1>Cadastrar novo anime</h1>
        {% csrf_token %}
        {{ form }}
    <button type="submit">Salvar</button>
    </form>
</div>
{% include 'animes/footer.html' %}
</body>
</html>

choose_anime/templates/animes/head.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'animes/style.css' %}">
    <title>Choose an anime to watch</title>
</head>

choose_anime/templates/animes/home.html
{% include 'animes/head.html' %}
<body>
    <main class="container">
        <h1>Animes já adicionados</h1>
        <div class="table-container">
            <table border="1">
                <tr>
                    <td class="title-1">Título</td>
                    <td class="title">Categoria</td>
                </tr>
                {% for a in anime %}
                    <tr>
                        <td>{{ a.title }}</td>
                        <td>{{ a.category }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </main>
{% include 'animes/footer.html' %}
</body>
</html>

choose_anime/templates/animes/random.html
{% include 'animes/head.html' %}
<body>
    <main class="container-random">
        <p>Pressione F5 para gerar um novo anime</p>
        <h1>{{ item }}</h1>
    </main>
{% include 'animes/footer.html' %}
</body>
</html>